name: firebase_backend
description: "Abstrações declarativas para Firestore, Firebase Auth e Firebase Storage: endpoints tipados, DTOs com validação, transactions e tratamento de erros unificado."
version: 0.1.0
homepage: https://github.com/triplegtech/firebase-backend
repository: https://github.com/triplegtech/firebase-backend
issue_tracker: https://github.com/triplegtech/firebase-backend/issues

environment:
  sdk: ^3.9.2
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_auth: ^6.1.2
  firebase_app_check: ^0.4.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_cloud_firestore: ^4.2.0
  firebase_auth_mocks: ^0.15.2
  firebase_storage_mocks: ^0.8.1
  mock_exceptions: ^0.8.2

flutter:
